### ISSUE TITLE
`Error: [Polly] [adapter:xhr] XHR global not found.`

### ISSUE THREAD

**Issue by bokece** [Netflix/pollyjs#199]
## Description
I use TestCafe for the execution of my tests but i get the following error even if the XHR adapter is registered.

Should polly.js be compatible with TestCafe? 
I have tried to find other users with similar error but no results.

`Error: [Polly] [adapter:xhr] XHR global not found.`

### Error Message & Stack Trace

```
      Error: [Polly] [adapter:xhr] XHR global not found.
      Browser: HeadlessChrome 73.0.3683 / Windows 10.0.0

         1 |export default function(msg, condition) {
         2 |  if (!condition) {
       > 3 |    throw new Error(`[Polly] ${msg}`);
         4 |  }
         5 |}
         6 |

         at Object.assert (...\@pollyjs\utils\src\utils\assert.js:3:11)
         at XHRAdapter.assert (...\@pollyjs\adapter\src\index.js:207:5)
         at XHRAdapter.assert [as onConnect] (...\@pollyjs\adapter-xhr\src\index.js:16:10)
         at XHRAdapter.onConnect [as connect] (...\@pollyjs\adapter\src\index.js:44:12)
         at Polly.connect [as connectTo] (...\@pollyjs\core\src\polly.js:269:13)
         at connectTo (...\@pollyjs\core\src\polly.js:165:50)
         at Polly.forEach [as configure] (...\@pollyjs\core\src\polly.js:165:26)
         at new configure (...\@pollyjs\core\src\polly.js:49:10)
   
```

### Config

Copy the config used to setup the Polly instance:

```js
import { Polly } from '@pollyjs/core';

 const FetchAdapter = require('@pollyjs/adapter-fetch')
 const XHRAdapter   = require('@pollyjs/adapter-xhr')
 const FSPersister = require('@pollyjs/persister-fs')
.....


  const polly = new Polly('Hello Polly', {
    adapters: ['xhr'],
    persister: 'fs',
    logging: true
  });

    polly.configure({ recordIfMissing: true,
    persisterOptions: {
      fs: {
        recordingsDir: '__recordings__'
      }
    }
  });

});
```

### Dependencies

Copy the @pollyjs dependencies from `package.json`:

```json
{
    "@pollyjs/adapter-fetch": "^2.3.1",
    "@pollyjs/adapter-xhr": "^2.3.0",
    "@pollyjs/core": "^2.3.0",
    "@pollyjs/persister-fs": "^2.1.0",
    "@types/pollyjs__core": "^2.3.0"
}
```

## Environment

Node.js v10.13.0
win32 10.0.17763
npm: 6.4.1
yarn: 1.13.0

**Comment by offirgolan** [comment]
Im not familiar with TestCafe but I'm assuming that the browser context is not within the same one as the one the polly instance is running on. The fetch adapter currently supports passing it a context:

```
new Polly('Recording Name', {
  adapters: ['fetch'],
  adapterOptions: {
    fetch: { context }
  }
});
```

Where the `context` is where polly should fine the necessary globals to override. Does TestCafe give you access to the running browser window?

**Comment by jasonmit** [comment]
Closing as the issue went stale.
