### ISSUE TITLE
Cannot read property 'shouldPassthrough' of undefined

### ISSUE THREAD

**Issue by claudijo** [Netflix/pollyjs#211]
Trying to run polly.JS (v2.3.0) with a puppeteer (v1.17.0 ) and puppeteer adapter (v2.4.0), I get the following error:

```
..(node:40715) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'shouldPassthrough' of undefined
    at PuppeteerAdapter.shouldPassthrough (<project>/node_modules/@pollyjs/adapter-puppeteer/node_modules/@pollyjs/adapter/src/index.js:127:19)
    at PuppeteerAdapter.handleRequest (<project>/node_modules/@pollyjs/adapter-puppeteer/node_modules/@pollyjs/adapter/src/index.js:102:13)
    at <anonymous>
```

Looking at the related code from the above error message (https://github.com/Netflix/pollyjs/blob/master/packages/%40pollyjs/adapter/src/index.js#L127) I can´t see that the [`_interceptor` property](https://github.com/Netflix/pollyjs/blob/master/packages/%40pollyjs/adapter/src/index.js#L114) in the `pollyRequest` object is set anywhere in your code.

Relevant setup in my application code is as follows: 
```
export function setupPollyPuppeteer(puppeteer, scope = {}) {
  const headless = false;
  const slowMo = 5;

  Before(async function({ pickle }) {
    scope.browser = await puppeteer.launch({
      headless,
      slowMo,
    });

    scope.context.currentPage = await scope.browser.newPage();
    scope.context.currentPage.setViewport({ width: 1280, height: 1024 });
    await scope.context.currentPage.setRequestInterception(true);

    scope.polly = new Polly(pickle.name, {
      adapters: ['node-http', 'puppeteer'],
      adapterOptions: {
        puppeteer: {
          page: scope.context.currentPage,
        },
      },
      persister: 'fs',
    });

    // const { server } = scope.polly;
    // configureServer(server);
  });

  After(async function() {
    if (scope.browser) {
      if (scope.context.currentPage) {
        // if it has, find all the cookies, and delete them
        const cookies = await scope.context.currentPage.cookies();
        if (cookies && cookies.length > 0) {
          await scope.context.currentPage.deleteCookie(...cookies);
        }
        // close the web page down
        await scope.context.currentPage.close();
      }

      await scope.browser.close();
    }

    await scope.polly.stop();
  });
}
```

**Comment by offirgolan** [comment]
@claudijo can you upgrade all your @pollyjs packages to their latest version? That should resolve this issue.

**Comment by claudijo** [comment]
@offirgolan Ok. Thanks
