### ISSUE TITLE
Only intercept required requests and let pass others

### ISSUE THREAD

**Issue by VikalpP** [Netflix/pollyjs#224]
I just want to intercept the request for `https://jsonplaceholder.typicode.com/posts/*`.
It's working fine for request related to `posts`.

But when the network request fires for `https://jsonplaceholder.typicode.com/comments/1`, It fails with 
 `(failed) net::ERR_FAILED`.

So, I'm just wondering why it stops network request for `comments`, while I've set up to intercept just for `posts`.

###  Source Code

```js
class Polly {

 async _connectPuppeteer(title) {
   const adapter = require('@pollyjs/adapter-puppeteer');

    PollyJS.register(adapter);
    const { page } = this.helpers.Puppeteer;
    await page.setRequestInterception(true);

    this.polly = new PollyJS(title, {
      adapters: ['puppeteer'],
      adapterOptions: {
        puppeteer: { page },
      },
    });
  }

  async interceptRequest(statusCode) {
    const { server } = this.polly;
    const handler = server.get('https://jsonplaceholder.typicode.com/posts/*');
    handler.intercept((_, res) => res.sendStatus(statusCode));
  }
}

```

### Error Message & Stack Trace

```sh
(node:21254) UnhandledPromiseRejectionWarning: Error: [Polly] [adapter:puppeteer] A persister must be configured in order to record and replay requests.
    at Object.assert (/home/oem/Desktop/Vikalp/CodeceptJS/node_modules/@pollyjs/utils/dist/cjs/pollyjs-utils.js:80:11)
    at PuppeteerAdapter.assert (/home/oem/Desktop/Vikalp/CodeceptJS/node_modules/@pollyjs/adapter/dist/cjs/pollyjs-adapter.js:1261:11)
    at PuppeteerAdapter.<anonymous> (/home/oem/Desktop/Vikalp/CodeceptJS/node_modules/@pollyjs/adapter/dist/cjs/pollyjs-adapter.js:1202:10)
    at PuppeteerAdapter.handleRequest (/home/oem/Desktop/Vikalp/CodeceptJS/node_modules/@pollyjs/adapter/dist/cjs/pollyjs-adapter.js:1173:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:21254) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:21254) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Screenshot of Error (onClick `GET COMMENTS`)
![Screenshot_20190705_130608](https://user-images.githubusercontent.com/11846339/60706329-ddc8aa80-9f26-11e9-87ba-cb74083d8d77.png)

### Dependencies

```json
{
  "@pollyjs/adapter-puppeteer": "^2.5.0",
  "@pollyjs/core": "^2.5.0",
}
```

## Environment

```sh
Node.js: v10.15.3
Operating: linux 4.18.0-20-generic
npm: 6.9.0
```

**Comment by offirgolan** [comment]
By default, Polly's recording mode is set to `replay` which requires a persister to save requests. You can set the initial recording mode to `passthrough` like so:

```diff
this.polly = new PollyJS(title, {
+     mode: 'passthrough',
      adapters: ['puppeteer'],
      adapterOptions: {
        puppeteer: { page },
      },
    });
```

**Comment by VikalpP** [comment]
Thanks, that resolved my problem.
