### ISSUE TITLE
recommended way to disable request capture errors with puppeteer/node

### ISSUE THREAD

**Issue by jordangarside** [Netflix/pollyjs#266]
Hey there,

I'm trying to use pollyjs with puppeteer and I'm encountering a problem, some non-critical requests are erroring out when changing the page with puppeteer's `goto()`. This is happening even in `passthrough` mode.
```sh
  console.group node_modules/@pollyjs/core/dist/cjs/pollyjs-core.js:2296
        Errored ➞ POST https://www.google-analytics.com/collect

  console.error node_modules/@pollyjs/core/dist/cjs/pollyjs-core.js:2297
        { errorText: 'net::ERR_ABORTED' }
```
I'm not sure exactly what this error is indicating either.

This causes the whole test to fail. I'm wondering if there is an easy way to have polly ignore requests for this url, or disable throwing errors selectively or entirely.

The test is fairly simple:
```js
it('should do something', async () => {
  await page.setBypassCSP(true)
  await page.setRequestInterception(true)
  const polly = await new Polly(
    `should-do-something`,
    {
      mode: 'passthrough',
      adapters: ['puppeteer'],
      adapterOptions: {
        puppeteer: { page },
      },
      recordFailedRequests: true,
      logging: false,
    }
  )
  await page.goto('http://localhost:3000')
  await page.goto('http://localhost:3000')
})
```

Package versions:
```
"@pollyjs/adapter-puppeteer": "2.6.3",
"@pollyjs/core": "2.6.3",
"@pollyjs/persister-fs": "2.6.3",
"jest": "24.9.0",
"jest-puppeteer": "4.3.0",
"puppeteer": "1.20.0",
```

Trace:
```
    Evaluation failed: TypeError: Failed to fetch

      at ExecutionContext._evaluateInternal (../../node_modules/puppeteer/lib/ExecutionContext.js:122:13)
        -- ASYNC --
      at ExecutionContext.<anonymous> (../../node_modules/puppeteer/lib/helper.js:111:15)
      at DOMWorld.evaluate (../../node_modules/puppeteer/lib/DOMWorld.js:112:20)
        -- ASYNC --
      at Frame.<anonymous> (../../node_modules/puppeteer/lib/helper.js:111:15)
      at Page.evaluate (../../node_modules/puppeteer/lib/Page.js:833:43)
      at Page.<anonymous> (../../node_modules/puppeteer/lib/helper.js:112:23)
      at evaluate (../../node_modules/@pollyjs/adapter-puppeteer/src/index.js:171:14)
      at new F (../../node_modules/core-js/library/modules/_export.js:36:28)
      at PuppeteerAdapter.passthroughRequest (../../node_modules/@pollyjs/adapter-puppeteer/src/index.js:166:30)
      at PuppeteerAdapter.passthroughRequest [as onPassthrough] (../../node_modules/@pollyjs/adapter/src/index.js:269:33)
      at PuppeteerAdapter.onPassthrough [as passthrough] (../../node_modules/@pollyjs/adapter/src/index.js:129:17)
      at PuppeteerAdapter.passthrough (../../node_modules/@pollyjs/adapter/src/index.js:104:19)
        -- ASYNC --
      at Page.<anonymous> (../../node_modules/puppeteer/lib/helper.js:111:15)
      at evaluate (../../node_modules/@pollyjs/adapter-puppeteer/src/index.js:171:14)
      at new F (../../node_modules/core-js/library/modules/_export.js:36:28)
      at PuppeteerAdapter.passthroughRequest (../../node_modules/@pollyjs/adapter-puppeteer/src/index.js:166:30)
      at PuppeteerAdapter.passthroughRequest [as onPassthrough] (../../node_modules/@pollyjs/adapter/src/index.js:269:33)
      at PuppeteerAdapter.onPassthrough [as passthrough] (../../node_modules/@pollyjs/adapter/src/index.js:129:17)
      at PuppeteerAdapter.passthrough (../../node_modules/@pollyjs/adapter/src/index.js:104:19)
      at PuppeteerAdapter.handleRequest (../../node_modules/@pollyjs/adapter/src/index.js:78:13
```

If this is a non-trivial case I can make a repro.

**Comment by jordangarside** [comment]
It looks like the error comes from navigating to new pages when requests are still pending. A work-around involves:
1. `goto('localhost:3000')`
2. `polly.stop()`
3. `goto('about:blank')`
4. `polly.start(...)`
5. `goto('localhost:3000')`
It seems like this shouldn't be necessary?

**Comment by jasonmit** [comment]
@jordangarside do you not see these errors without Polly instantiated?  Are the requests settled by the time the next `goto` occurs?

`await polly.flush()` between `goto`'s may also be more appropriate vs stopping and restarting.

**Comment by jordangarside** [comment]
The requests are not settled when the next `goto` occurs, causing the issues.

No errors when Polly is not instantiated.

`await polly.flush()` hangs indefinitely because those requests aren't resolving.

**Comment by jasonmit** [comment]
> The requests are not settled when the next goto occurs, causing the issues.

Just to be clear this happens even when Polly isn't used?

> await polly.flush() hangs indefinitely because those requests aren't resolving.

Intentionally held open requests or a bug?

**Comment by jordangarside** [comment]
> Just to be clear this happens even when Polly isn't used?

This does not happen when Polly isn't used.

> Intentionally held open requests or a bug?

This happens in both cases where the connection is intentionally and unintentionally held open. I basically just want to disregard requests that haven't resolved.

In the case where I load a page and then immediately load the next page, I haven't waited for all requests to resolve. This causes Polly to crash at the moment.

**Comment by jordangarside** [comment]
It actually turns out that one of the specific request causing this problem for me is actually being hung by Polly.

`https://www.google-analytics.com/collect`

It doesn't hang when Polly is not initialized.

### This is what the request looks like when it goes through:
![image](https://user-images.githubusercontent.com/6321824/67245875-ea0f3f80-f411-11e9-9e06-f082f6fa596c.png)

### And when it fails:
![image](https://user-images.githubusercontent.com/6321824/67246055-48d4b900-f412-11e9-80a5-c65c0bfa63c7.png)

**Comment by jordangarside** [comment]
It seems like Polly is not calling `request.continue()` for this specific request.

If I add this:
```
    page.on('request', request => {
      if (
        !request._interceptionHandled &&
        request._url === 'https://www.google-analytics.com/collect'
      ) {
        request.continue()
      }
    })
```

Then the request resolves.

**Comment by jasonmit** [comment]
Seems related to the same issue in https://github.com/Netflix/pollyjs/issues/248 where a google POST request never resolves.  I still have not uncovered why that is.

**Comment by jordangarside** [comment]
Interesting.

Is there any way to not throw errors when requests are aborted? I'd still like to be able to navigate to new pages while their are pending requests and simply drop those (instead of error out).

**Comment by jasonmit** [comment]
I don't believe it's Polly that's throwing, it's the fact that the request hasn't settled when transitioning away because of the same issue in #248 and so Chrome throws.  I may not be correct about this but that's what I believe is happening.

**Comment by jasonmit** [comment]
Closing in favor of tracking core issue in #248
