### ISSUE TITLE
How to switch off logs for mockRequest in codeceptjs + puppeteer?

### ISSUE THREAD

**Issue by aelzhanova** [Netflix/pollyjs#314]
## Prerequisites

helpers: {
    Puppeteer: {
      url: process.env.CODECEPT_URL || 'http://seller-ui.sc.stg.s.o3.ru',
      show: false,
      browser: 'chrome',
      windowSize: '1920x1080',
      waitForAction: 0,
      waitForNavigation: 'load',
      restart: false,
      keepBrowserState: true,
      typeInterval: '-1',
      chrome: {
        args: ['--no-sandbox', '--headless', '--window-size=1920,1080', '--disable-web-security'],
      },
      capabilities: {
        chromeOptions: {
          w3c: false,
        },
      },
    },
    MockRequest: {
      mode: 'passthrough',
      logging: false,
      recordIfMissing: false,
      recordFailedRequests: false,
    },

## Description

When I run tests that using MockRequest I get very big logs, that contains everything - my request and response and all images in response. I don't need it, I want small logs without it. 
Also after each request I get error in logs:
UnhandledPromiseRejectionWarning: Error: Request Interception is not enabled!

### Shareable Source

```js
// Avoid posting hundreds of lines of source code.
// Edit to just the relevant portions.
```

### Error Message & Stack Trace

```
id: '1390c110deecf8652c41310288b789bc',
      order: 6,
      timestamp: '2020-03-17T07:08:26.713Z',
      responseTime: 203,
      [Symbol()]: URL {
        slashes: true,
        protocol: 'http:',
        hash: '',
        query: {},
        pathname: '/api/site/mailbox/topic/list',
        auth: '',
        host: 'seller-ui.sc.stg.s.o3.ru',
        port: '',
        hostname: 'seller-ui.sc.stg.s.o3.ru',
        password: '',
        username: '',
        origin: 'http://seller-ui.sc.stg.s.o3.ru',
        href: 'http://seller-ui.sc.stg.s.o3.ru/api/site/mailbox/topic/list'
      },
      [Symbol()]: <ref *1> Polly {
        logger: Logger {
          polly: [Circular *1],
          groupName: 'Test',
          _middleware: [Handler [Map]]
        },
        server: Server {
          [Symbol()]: '',
          [Symbol()]: [Object],
          [Symbol()]: [],
          [Symbol()]: [Array]
        },
        config: {
          mode: 'passthrough',
          adapters: [Array],
          adapterOptions: [Object],
          persister: null,
          persisterOptions: [Object],
          logging: false,
          recordIfMissing: false,
          recordFailedRequests: false,
          expiresIn: null,
          expiryStrategy: 'warn',
          timing: [Function (anonymous)],
          matchRequestsBy: [Object]
        },
        container: Container { _registry: [Map] },
        adapters: Map { _c: [Map] },
        persister: null,
        _requests: [
          [PollyRequest], [PollyRequest], [PollyRequest],
          [PollyRequest], [PollyRequest], [PollyRequest],
          [PollyRequest], [PollyRequest], [PollyRequest],
          [PollyRequest], [PollyRequest], [PollyRequest],
          [PollyRequest], [PollyRequest], [PollyRequest],
          [PollyRequest], [PollyRequest], [PollyRequest],
          [PollyRequest], [PollyRequest], [PollyRequest],
          [PollyRequest], [PollyRequest], [PollyRequest],
          [PollyRequest], [PollyRequest], [PollyRequest],
          [PollyRequest], [PollyRequest], [PollyRequest],
          [PollyRequest], [PollyRequest], [PollyRequest],
          [PollyRequest], [PollyRequest], [PollyRequest],
          [Circular *2]
        ],
        [Symbol()]: 'Test',
        [Symbol()]: 'Test_805092869'
      },
      [Symbol()]: EventEmitter {
        [Symbol()]: Map { _c: [Map] },
        [Symbol()]: Set { _c: [Set] }
      },
      [Symbol()]: Route {
        params: {},
        queryParams: {},
        handlers: [],
        middleware: [ [Route] ],
        [Symbol()]: [ [Object] ]
      }
    }
    Response: PollyResponse {
      headers: {
        date: 'Tue, 17 Mar 2020 07:08:26 GMT',
        'content-encoding': 'gzip',
        server: 'nginx/1.17.7',
        vary: 'Origin, Accept-Encoding, Origin',
        'content-type': 'application/json',
        'access-control-allow-origin': 'http://seller-ui.sc.stg.s.o3.ru',
        'access-control-expose-headers': 'X-O3-Trace-Id',
        'transfer-encoding': 'chunked',
        connection: 'keep-alive',
        'access-control-allow-credentials': 'true',
        'x-o3-trace-id': '6e1dda4a844febbf, 6e1dda4a844febbf'
      },
      statusCode: 200,
      body: bigbigbig body....
(node:51520) UnhandledPromiseRejectionWarning: Error: Request Interception is not enabled!
      at assert (/Users/aelzhanova/Documents/Projects/seller-ui/__tests__/codeceptjsTests/node_modules/puppeteer/lib/helper.js:283:11)
      at Request.abort (/Users/aelzhanova/Documents/Projects/seller-ui/__tests__/codeceptjsTests/node_modules/puppeteer/lib/NetworkManager.js:494:5)
      at Request.<anonymous> (/Users/aelzhanova/Documents/Projects/seller-ui/__tests__/codeceptjsTests/node_modules/puppeteer/lib/helper.js:112:23)
      at PuppeteerAdapter.respondToRequest (/Users/aelzhanova/Documents/Projects/seller-ui/__tests__/codeceptjsTests/node_modules/@pollyjs/adapter-puppeteer/dist/cjs/pollyjs-adapter-puppeteer.js:2397:21)
      at PuppeteerAdapter.onRequestFailed (/Users/aelzhanova/Documents/Projects/seller-ui/__tests__/codeceptjsTests/node_modules/@pollyjs/adapter/dist/cjs/pollyjs-adapter.js:1394:18)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async PuppeteerAdapter.handleRequest (/Users/aelzhanova/Documents/Projects/seller-ui/__tests__/codeceptjsTests/node_modules/@pollyjs/adapter/dist/cjs/pollyjs-adapter.js:1167:7)
  (node:51520) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 95)
```

### Config

Copy the config used to setup the Polly instance:

```js
new Polly('Recording Name', {
  // config...
});
```

### Dependencies

Copy the @pollyjs dependencies from `package.json`:

```json
{
  "@pollyjs/core": "latest",
  "@pollyjs/adapter-x": "latest",
  "@pollyjs/persister-x": "latest"
}
```

## Relevant Links

- If your project is public, link to the repo so we can investigate directly.
- **BONUS POINTS:** Create a [minimal reproduction](http://stackoverflow.com/help/mcve) and upload it to GitHub. This will get you the fastest support.

## Environment

Tell us which operating system you are using, as well as which versions of Node.js and npm/yarn. If applicable, include the browser and the corresponding version.

Run the following to get it quickly:

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
npm --version
yarn --version

Node.js v13.8.0
darwin 18.7.0
6.13.7
1.22.0

 "dependencies": {
    "@pollyjs/adapter-puppeteer": "^4.0.2",
    "chai": "^4.2.0",
    "codeceptjs": "^2.5.0",
    "codeceptjs-resemblehelper": "^1.9.0",
    "eslint-config-google": "^0.14.0",
    "mocha": "^7.0.1",
    "node-fetch": "^2.6.0",
    "puppeteer": "^2.1.1"
  },
  "devDependencies": {
    "@pollyjs/core": "^2.5.0",
    "@codeceptjs/configure": "^0.4.1",
    "eslint": "^6.8.0",
    "mochawesome": "^4.1.0"
  },
  "engines": {
    "node": ">=8.0.0"
  }
}
```

**Comment by jasonmit** [comment]
The large stacktrace is caused by the stringifying of a Polly object in the error.  Unsure why that is, would need to investigate further - we can likely improve the error messaging.

The exception you are seeing (`UnhandledPromiseRejectionWarning: Error: Request Interception is not enabled!`) is likely caused because you haven't yet invoked `page.setRequestInterception(true);`

An example of that https://github.com/Netflix/pollyjs/blob/6420b59f5534b918a524a169e12d30a648c62414/examples/puppeteer/index.js#L15

**Comment by aelzhanova** [comment]
Where I should paste it?
I created my custom helper and use this function before I.mock and after I.mock and still get this error
> const Helper = codecept_helper;
> // const puppeteer = require('puppeteer');
> 
> class MyHelper extends Helper {
>   async setInterception() {
>     const { page } = this.helpers.Puppeteer;
>     await page.setRequestInterception(true);
>   }

**Comment by jasonmit** [comment]
@aelzhanova that looks like an incomplete snippet, it's hard to say why this is happening.  Are you passing this `page` object to Polly?  Example:

https://netflix.github.io/pollyjs/#/adapters/puppeteer?id=usage
