### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by hnguyen14** [Netflix/pollyjs#439]
## Description
I'm trying to write a functional test with using PollyJS to record external API network calls and replays. In doing so, I'm using fs-persister which ultimately uses fs-extra.  when running the test, I got a error that seems to be related to universalify

I'm using node version 14.15.3

### Shareable Source
startPolly.js
```
import path from 'path';
import FSPersister from '@pollyjs/persister-fs';
import NodeHttpAdapter from '@pollyjs/adapter-node-http';

import { MODES } from '@pollyjs/utils';
import { Polly } from '@pollyjs/core';
import { setupPolly, Context } from 'setup-polly-jest';

Polly.register(NodeHttpAdapter);
Polly.register(FSPersister);

export default function startPolly(): Context {
  const recordingsDir = path.resolve(__dirname, '__mocks__');
  return setupPolly({
    mode: MODES.REPLAY,
    recordIfMissing: process.env.POLLYJS_RECORD_IF_MISSING === 'true',
    recordFailedRequests: true,
    adapters: ['node-http'],
    persister: 'fs',
    persisterOptions: {
      fs: { recordingsDir },
    },
  });
}
```

and in the test
```
describe('...', () => {
    const context = startPolly();
    it('...', async () => {
        ..
    })
})
```

### Error Message & Stack Trace

    TypeError: Cannot read property 'name' of undefined

      1 | import path from 'path';
    > 2 | import FSPersister from '@pollyjs/persister-fs';
        | ^
      3 | import NodeHttpAdapter from '@pollyjs/adapter-node-http';
      4 | 
      5 | import { MODES } from '@pollyjs/utils';

      at Object.<anonymous>.exports.fromCallback (node_modules/@pollyjs/node-server/node_modules/universalify/index.js:15:26)
      at Object.<anonymous> (node_modules/@pollyjs/node-server/node_modules/fs-extra/lib/fs/index.js:57:27)
      at Object.<anonymous> (node_modules/@pollyjs/node-server/node_modules/fs-extra/lib/index.js:5:6)
      at Object.<anonymous> (node_modules/@pollyjs/node-server/dist/cjs/pollyjs-node-server.js:15:26)
      at Object.<anonymous> (node_modules/@pollyjs/persister-fs/dist/cjs/pollyjs-persister-fs.js:13:18)
      at Object.<anonymous> (functional/startPolly.ts:2:1)
      at Object.<anonymous> (functional/sms.spec.ts:6:1)

### Dependencies

Copy the @pollyjs dependencies from `package.json`:

```json
{
  "@pollyjs/adapter-node-http": "^6.0.2",
  "@pollyjs/core": "^6.0.2",
  "@pollyjs/persister-fs": "^6.0.2",
  "@pollyjs/utils": "^6.0.1",
}
```

## Environment

Node.js v14.15.3
darwin 20.6.0
NPM version - 6.14.9

**Comment by hnguyen14** [comment]
We were using `dd-trace` v0.33.2 which has a bug in which native is missing from fs.realpath. Upgrading to v0.34.0 fix this exact problem

https://github.com/DataDog/dd-trace-js/releases/tag/v0.34.0
