### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by spsch** [Netflix/pollyjs#59]
Hi, please can you help me with dummy explanation how to run pollyjs tests in mocha? I am trying to execute this short script (with all modules installed globally via npm 5.6.0 / node  v8.11.1):

`var Polly = require('@pollyjs/core');

describe('VALO login',  function () {

    it('vp admin sign in true', async function() {
        const polly = new Polly('App log in', {
            persisterOptions: {
                host: 'http://v2appenv01',
            }
        });

        await visit('/#/');
        await fillIn('username','test.admin');
        await fillIn('password','password');
        await submit();

        expect(location.pathname).to.equal('/#/list');

        await polly.stop();

    });

});`

and the results is:

`mocha polly_login_test.js
C:\Users\spsch\AppData\Roaming\npm\node_modules\@pollyjs\core\src\polly.js:1
(function (exports, require, module, __filename, __dirname) { import mergeOptions from 'merge-options';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\spsch\code\valo\src\test\javascript\e2e\prague_test\polly_login_test.js:4:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at C:\Users\spsch\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\spsch\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:247:14)
    at Mocha.run (C:\Users\spsch\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:576:10)
    at Object.<anonymous> (C:\Users\spsch\AppData\Roaming\npm\node_modules\mocha\bin\_mocha:637:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3`

Thank you in advance.

**Comment by offirgolan** [comment]
@spsch are you running this in the browser or in node?

**Comment by jasonmit** [comment]
What are you also using to bundle your app?

The bundler is resolving pollyjs/core to the ES entry point.  If you're using a browser, use the UMD dist.  If node, use the commonjs dist.

https://github.com/Netflix/pollyjs/blob/master/packages/%40pollyjs/core/package.json#L5-L7

**Comment by spsch** [comment]
The app is based on nodejs and many build tools are used (gulp, bower, npm and yarn). It seems that main bundler is yarn and tests are done via gulp tasks. I would like to run it from shell/cmd, so node seems to be best option. Thank you for your response, I am not JS developer originally, so I am going to educate myself; anyway any other help is appreciated :-)

**Comment by jasonmit** [comment]
@spsch it's unclear without looking at your project as to what is resolving the package to the incorrect entry point.  Is this project open source or can you share?

**Comment by jasonmit** [comment]
Closing since this is the user's bundler choosing the wrong entry point for Polly.
