### ISSUE TITLE
Puppeteer adapter + Rest persister does not work.

### ISSUE THREAD

**Issue by harunurhan** [Netflix/pollyjs#81]
The problem is that `global.XMLHttpRequest` which rest persister uses is not defined. I have tried adding `xhr` adapter, jus to see if it will make a difference, but I got `[Polly] [adapter:xhr] XHR global not found` because I use `puppeteer`

### options
```js
{
      adapters: ['puppeteer'],
      persister: 'rest',
      adapterOptions: {
        puppeteer: { page },
      },
      persisterOptions: {
        rest: {
          host: 'http://localhost:8080',
        },
      },
}
```

### error
```
TypeError: NativeXMLHttpRequest is not a constructor

      at _Promise (node_modules/@pollyjs/persister-rest/dist/cjs/pollyjs-persister-rest.js:1289:17)
      at new F (node_modules/@pollyjs/persister-rest/dist/cjs/pollyjs-persister-rest.js:210:28)
      at ajax (node_modules/@pollyjs/persister-rest/dist/cjs/pollyjs-persister-rest.js:1288:10)
      at RestPersister.ajax (node_modules/@pollyjs/persister-rest/dist/cjs/pollyjs-persister-rest.js:1345:12)
      at node_modules/@pollyjs/persister-rest/dist/cjs/pollyjs-persister-rest.js:1352:36
      at step (node_modules/@pollyjs/persister-rest/dist/cjs/pollyjs-persister-rest.js:1227:30)
      at node_modules/@pollyjs/persister-rest/dist/cjs/pollyjs-persister-rest.js:1245:14
```

**Comment by harunurhan** [comment]
@offirgolan 

Thanks for the quick response! Apparently I just misunderstood docs somehow.

I will try it with `fs` and then close the issue if it works.

**Comment by harunurhan** [comment]
Changing to `fs` fixed the previous error, but got a new one related with `puppeteer` adapter. [adapter-puppeteer/src/index.js#L85](https://github.com/Netflix/pollyjs/blob/master/packages/%40pollyjs/adapter-puppeteer/src/index.js#L85) is blowing up. I am going to investigate as soon as I have time but maybe you already have an idea why? @offirgolan 

### config
```js
function createPollyInstance(recordingName) {
  return new Polly(recordingName, {
    adapters: [PuppeteerAdapter],
    persister: FSPersister,
    adapterOptions: {
      puppeteer: { page },
    },
    persisterOptions: {
      fs: {
        recordingsDir: '__api_recordings__',
      },
    },
  });
}
```
It's actually an open source project, so here's the branch with `pollyjs`, https://github.com/harunurhan/inspirehep-ui/tree/pollyjs

### error.
```
    TypeError: Cannot read property 'resolve' of undefined

      at Page.requestfinished (node_modules/@pollyjs/adapter-puppeteer/dist/cjs/pollyjs-adapter-puppeteer.js:2224:42)
      at NetworkManager.Page._networkManager.on.event (node_modules/puppeteer/lib/Page.js:96:82)
      at NetworkManager._onLoadingFinished (node_modules/puppeteer/lib/NetworkManager.js:282:10)
      at CDPSession._onMessage (node_modules/puppeteer/lib/Connection.js:219:12)
```

**Comment by offirgolan** [comment]
@harunurhan can you bump all your @pollyjs packages to their latest versions? That should resolve the issue you're running into.

**Comment by harunurhan** [comment]
Thanks! that solved it!
