### ISSUE TITLE
TypeError: Invalid value used as weak map key

### ISSUE THREAD

**Issue by mfestrada** [Netflix/pollyjs#98]
Hi,

While trying this out, I got the error ```TypeError: Invalid value used as weak map key```

My test code looks roughly like:

```javascript
const puppeteer = require('puppeteer');
const Polly = require('@pollyjs/core').Polly;
const { PuppeteerAdapter } = require('@pollyjs/adapter-puppeteer');

// skipping setup/teardown in this example
it('does foo', async function() {
  let page = await browser.newPage();

  Polly.register(PuppeteerAdapter);
  await page.setRequestInterception(true);

  const polly = new Polly('first_recording', {
    adapters: ['puppeteer'],
    adapterOptions: {
      puppeteer: { page }
    }
  });

  polly.connectTo('puppeteer');
  await page.goto('http://example.com');
  polly.disconnectFrom('puppeteer');

});

```

The stack trace:
```shell
     TypeError: Invalid value used as weak map key
      at WeakMap.set (native)
      at WeakMap.<anonymous> (node_modules/@pollyjs/core/dist/cjs/pollyjs-core.js:1586:34)
      at Function.register (node_modules/@pollyjs/core/dist/cjs/pollyjs-core.js:4054:28)
      at Context.<anonymous> (test/pollyjs-hello-world.js:129:13)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

I'm running node v8.11.3.  Help!

**Comment by jasonmit** [comment]
Change:

`const { PuppeteerAdapter } = require('@pollyjs/adapter-puppeteer');`

to

`const PuppeteerAdapter = require('@pollyjs/adapter-puppeteer');`

Feel free to comment/reopen if this doesn't address your issue.
